### ISSUE TITLE
Can not import ranges plugin

### ISSUE THREAD

**Issue by nikkii94** [wakirin/Litepicker#268]
**Describe the bug**
Hello, I got the following error message when I try to import the ranges plugin:

```
sealing chunk optimization SplitChunksPlugin(node:4559) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at Object.name [as getName] (webpack.common.v5.config.js:375:26)
    at addModuleToChunksInfoMap (node_modules/webpack/lib/optimize/SplitChunksPlugin.js:1029:31)
    at node_modules/webpack/lib/optimize/SplitChunksPlugin.js:1191:9
    at Hook.eval [as call] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:39:16)
    at Hook.CALL_DELEGATE [as _call] (node_modules/tapable/lib/Hook.js:14:14)
    at Compilation.seal (node_modules/webpack/lib/Compilation.js:2415:36)
    at node_modules/webpack/lib/Compiler.js:1109:20
    at node_modules/webpack/lib/Compilation.js:2227:4
    at eval (eval at create (node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:42:1)
    at node_modules/webpack/lib/FlagDependencyExportsPlugin.js:376:11
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4559) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4559) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

import Litepicker from 'litepicker';
import 'litepicker/dist/plugins/ranges';

If I comment out the ranges import everything works fine. I'm using litepicker@2.0.11

**To Reproduce**

**Expected behavior**

**jsfiddle.net / codepen.io / etc**
Please provide a link with bug.

**Additional context**

**Comment by nikkii94** [comment]
Turned out the problem was in my webpack configuration.
